- id: closeLights
  alias: turn off lights
  trigger:
  - at: '22:04:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: group.all_lights
    service: homeassistant.turn_off
- id: fb12a37448ee4d7ba33cf3024ec042ac
  alias: Power state on HA start-up
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      payload: ''
      qos: 1
      topic: sonoffs/cmnd/state
    service: mqtt.publish
  - data:
      message: HA restart
      title: Gross Home Assistant
    service: notify.telegram
- id: Living Room  Reset  motion
  alias: Living Room Reset  motion
  trigger:
  - entity_id: binary_sensor.livingroom_motion
    for: 00:01:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      payload: 7A4FE0off
      topic: RFbridge/tele/RESULT
    service: mqtt.publish
- id: Pergula   Reset motion
  alias: Pergula  Reset motion
  trigger:
  - entity_id: binary_sensor.pergula_motion
    for: 00:01:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      payload: 5C9DACoff
      topic: RFbridge/tele/RESULT
    service: mqtt.publish
- alias: Tal turn off  AC
  trigger:
  - platform: state
    entity_id: binary_sensor.tal_room_motion
    to: 'off'
    for:
      minutes: 15
  condition:
  - condition: state
    entity_id: climate.tal_room_ac
    state: 'on'
  action:
  - entity_id: climate.tal_room_ac
    service: climate.turn_off
  id: b90e4550954f4f5c9d8d073854290964
- id: boiler morning
  alias: BOILER Morning
  trigger:
  - at: 05:00:00
    platform: time
  condition:
  - condition: state
    entity_id: switch.boiler_switch
    state: 'off'
  - below: '44'
    condition: numeric_state
    entity_id: sensor.boiler_watertemp
  action:
  - data:
      message: מדליק דוד שמש
      title: Home Assistant
    service: notify.telegram
  - entity_id: switch.boiler_switch
    service: switch.turn_on
  - delay: 01:00:00
  - entity_id: switch.boiler_switch
    service: switch.turn_off
  - data:
      message: דוד שמש כבוי
      title: Home Assistant
    service: notify.telegram
- id: boiler Evening
  alias: BOILER Evening
  trigger:
  - at: '17:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: switch.boiler_switch
    state: 'off'
  - below: '44'
    condition: numeric_state
    entity_id: sensor.boiler_watertemp
  action:
  - data:
      message: דוד שמש דולק
      title: Home Assistant
    service: notify.telegram
  - entity_id: switch.boiler_switch
    service: switch.turn_on
  - delay: 01:00:00
  - entity_id: switch.boiler_switch
    service: switch.turn_off
  - data:
      message: דוד שמש כבוי
      title: Home Assistant
    service: notify.telegram
- id: Front Lights Turn On
  alias: Front Lights Turn On
  trigger:
  - event: sunset
    offset: 00:45:00
    platform: sun
  condition:
  - condition: state
    entity_id: group.front_lights
    state: 'off'
  action:
  - entity_id: group.front_lights
    service: switch.turn_on
  - delay: 02:00:00
  - entity_id: group.front_lights
    service: switch.turn_off
  - data:
      message: אור חצר קדמי דלוק
      title: Gross Home
    service: notify.telegram
- id: bed room Turn On Lights
  alias: Bedroom Turn On Lights morning
  trigger:
  - event: sunrise
    offset: -00:45:00
    platform: sun
  condition:
  - condition: state
    entity_id: switch.sockettemp_switch
    state: 'off'
  action:
  - entity_id: switch.sockettemp_switch
    service: switch.turn_on
  - delay: 01:00:00
  - entity_id: switch.sockettemp_switch
    service: switch.turn_off
  - data:
      message: morning Lights
      title: Gross Home Assistant
    service: notify.telegram
- id: Front  door Reset
  alias: ' Front Door Reset'
  trigger:
  - entity_id: binary_sensor.front_door_open
    for: 00:01:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      payload: 9D1489off
      topic: RFbridge/tele/RESULT
    service: mqtt.publish
- id: bedroom Reset Motion
  alias: bedroom Reset Motion
  trigger:
  - entity_id: binary_sensor.bedroom_motion
    for: 00:01:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      payload: AF90ACoff
      topic: RFbridge/tele/RESULT
    service: mqtt.publish
- id: Kitchen Reset Motion
  alias: Kitchen Reset Motion
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    for: 00:01:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      payload: EB66FEoff
      topic: RFbridge/tele/RESULT
    service: mqtt.publish
- id: living Room Reset AC Motion
  alias: ' Livingroom Reset AC  Motion sensor '
  trigger:
  - entity_id: binary_sensor.ac_living_room_on
    for: 00:01:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      payload: 4DC523off
      topic: RFbridge/tele/RESULT
    service: mqtt.publish
- id: backdoor Reset lock
  alias: Back Door Reset Lock
  trigger:
  - entity_id: binary_sensor.back_door_open
    for: 00:01:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      payload: 48F8B9off
      topic: RFbridge/tele/RESULT
    service: mqtt.publish
- id: talRoom Reset motion
  alias: Tal room Reset motion
  trigger:
  - entity_id: binary_sensor.tal_room_motion
    for: 00:01:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      payload: E9A7DEoff
      topic: RFbridge/tele/RESULT
    service: mqtt.publish
- id: Turn Off Tv's
  alias: Turn Off Tv's
  trigger:
  - at: 01:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: group.all_tv
    service: media_player.turn_off
- id: Hall smoke_detector_alarm reset
  alias: Hall Smoke Detector Alarm
  trigger:
  - entity_id: binary_sensor.hall_smoke_detector
    for: 00:01:00
    from: 'Off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Smoke Detector Alarm
      title: Gross Home Assistant
    service: notify.telegram
- id: keshet turn on movement
  alias: 'keshet turn on movement '
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    for: 00:00:01
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: sunset
    before: sunrise
    condition: sun
  action:
  - entity_id: switch.keshet_switch
    service: switch.turn_on
  - delay: 00:15:00
- id: '1568350425097'
  alias: kitchen smoke detector alarm
  trigger:
  - entity_id: binary_sensor.kitchen_smoke_detector_alarm
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: smoke detector kitchen alarm
      title: Gross Home Assistant
    service: notify.telegram
- id: bedroom No Movement Turn Of  fan
  alias: bedroom No Movement Turn Of  fan
  trigger:
  - entity_id: binary_sensor.bedroom_motion
    for: 00:15:00
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: switch.bedroomfan_switch
    state: 'on'
  action:
  - data:
      entity_id: switch.bedroomfan_switch
    entity_id: switch.bedroomfan_switch
    service: switch.turn_off
  - data:
      message: No Move bedroom  Fan Off
      title: Gross Home Assistant
    service: notify.telegram
- id: bedroom No MoveTurn Off bedroom aircondition
  alias: bedroom No Movement Turn Of  A/C
  trigger:
  - entity_id: binary_sensor.bedroom_motion
    for: 00:30:00
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: climate.bed_room_ac
    state: 'on'
  action:
  - data:
      entity_id: climate.bed_room_ac
    entity_id: climate.bed_room_ac
    service: climate.turn_off
  - data:
      message: No Move Bedroom Ac Off
      title: Gross Home Assistant
    service: notify.telegram
- id: Living Room No MoveTurn Off  aircondition
  alias: Livingroom No Movement Turn Of  A/C
  trigger:
  - entity_id: binary_sensor.livingroom_motion
    for: 00:30:00
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: climate.living_room_ac
    state: 'on'
  action:
  - data:
      entity_id: climate.living_room_ac
    entity_id: climate.living_room_ac
    service: climate.turn_off
  - data:
      message: No Move Living room Ac Off
      title: Gross Home Assistant
    service: notify.telegram
  - data:
      entity_id: climate.living_room_ac
    service: climate.turn_off
- id: '1569117562991'
  alias: 'Living room Ac movmentchange '
  trigger:
  - entity_id: binary_sensor.ac_living_room_on
    for: 0:05
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: climate.living_room_ac
    state: 'off'
  action:
  - data:
      entity_id: climate.living_room_ac
    service: climate.turn_on
- id: living room  power on  ac  motion sensor
  alias: living room  power on  ac  motion sensor
  trigger:
  - payload: 4DC523
    platform: mqtt
    topic: RFbridge/tele/RESULT
  condition:
  - condition: state
    entity_id: climate.living_room_ac
    state: 'off'
  action:
  - alias: ''
    data:
      entity_id: climate.living_room_ac
    service: climate.turn_on
- id: tal room  power on  ac  motion sensor
  alias: tal  room  power on  ac  motion sensor
  trigger:
  - payload: B16533
    platform: mqtt
    topic: RFbridge/tele/RESULT
  condition:
  - condition: state
    entity_id: climate.tal_room_ac
    state: 'off'
  action:
  - alias: ''
    data:
      entity_id: climate.tal_room_ac
    service: climate.turn_on
- id: Bedroom room  power on  ac  motion sensor
  alias: bed   room  power on  ac  motion sensor
  trigger:
  - payload: EB66FE
    platform: mqtt
    topic: RFbridge/tele/RESULT
  condition:
  - condition: state
    entity_id: climate.bedroom_room_ac
    state: 'off'
  action:
  - alias: ''
    data:
      entity_id: climate.bedroom_room_ac
    service: climate.turn_on
